name: Music Player Search CI/CD

on:
  push:
  #    branches:
  #      - "sub/*"
  #      - "feature/*"
  #      - "fix/*"

  pull_request:
    branches:
      #      - development
      - production
#      - master

jobs:
  build-search:
    name: Music Player Search Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x ]

    outputs:
      output1: ${{ steps.installed_dependencies.outputs }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      #      - name: Run the tests and generate coverage report
      #        run: npm run test-coverage

      #      - name: Upload coverage to Codecov
      #        uses: codecov/codecov-action@v1
      #        if: github.ref == 'refs/heads/production'
      #        with:
      #          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      - name: Build
        run: npm run build
        env:
          REACT_APP_SEARCH_ENV : ${{ secrets.REACT_APP_SEARCH_ENV }}
          AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}

      - name: Set tag name output
        id: set_tag_name
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Get version and push tag
        id: tag_version
        if: github.ref == 'refs/heads/production'
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        if: github.ref == 'refs/heads/production'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/production'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync AWS S3 bucket
        if: github.ref == 'refs/heads/production'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --exclude '.git*/*' --delete --follow-symlinks
        env:
          SOURCE_DIR: './dist'
          DEST_DIR: 'sub-app/search'
          AWS_REGION: 'us-east-1'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#      - name: Update AWS cloudfront cache with S3 bucket
#        if: github.ref == 'refs/heads/production'
#        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
